# Pre-procesamiento de datos discretos

Entendemos por datos discretos a aquellos tipos de datos que sólo pueden tomar un valor prefijado entre un conjunto finito o infinito de valores. Algunos ejemplos de datos discretos son:

- En el *método de pago de una compra online* hay que elegir entre pago contra-reembolso, pago con tarjeta, pago por trasferencia o pago con PayPal.
- La *edad de una persona* puede tomar valores 0, 1, 2, 3... hasta infinito. Aunque el conjunto de valores no esté acotado superiormente, estos datos son discreto, ya que la edad de una persona no se mide en número decimales.
- La *valoración de un usuario a un video de YouTube* se mide en me gusta o no me gusta.

Este tipo de datos, especialmente cuando no son numéricos, suelen ser problemáticos para la gran mayoría de algoritmos de *machine learning*. Casi todos los algoritmos se fundamentan en expresiones matemáticas que requieren operar con las características de las muestras. Por lo tanto, cuando se quiere realizar el producto de un datos que representa a un "*hombre*"* con uno que representa a una "*mujer*" sencillamente es imposible, ya que existen operaciones matemáticas definidas para esos valores.

## OneHotEncoder

Para solventar este problema se utiliza una técnica denominada como *One-Hot-Encoding* que consisten en dividir una característica en tantas características como posibles valores pueda tomar la característica original y asignar el valor 0 ó 1 a cada una de estas nuevas características en función del valor de la original.

Veamos esto con un ejemplo. Supongamos que tenemos las siguientes muestras:

| Nombre | Sexo |
| :---: | :---: |
| Alice | mujer |
| Bob | hombre |
| Carl | hombre |
| Denna | mujer |

La características *Sexo* se divide en las características *Hombre*  y *Mujer* que tomarán los siguientes valores:

| Nombre | Hombre | Mujer |
| :---: | :---: | :---: |
| Alice | 0 | 1 |
| Bob | 1 | 0 |
| Carl | 1 | 0 |
| Denna | 0 | 1 |

Como vemos, las nuevas características toman el valor 1 en la columna que coincide con el valor de la característica original.

Esta codificación puede llevarse a cabo empleando el objeto [preprocessing.OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder).

Cargamos la característica anterior en un array de *NumPy*:

In [1]:
import numpy as np

X = np.array([['mujer' ],
              ['hombre'],
              ['hombre'],
              ['mujer' ]])

Y aplicamos la transformación:

In [2]:
from sklearn.preprocessing import OneHotEncoder

OneHotEncoder().fit_transform(X).toarray()

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

## OrdinalEncoder

Otra alternativa es emplear [`OrdinalEnconder`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html), el cual transforma cada uno de los posibles valores de la característica en un entero:

In [3]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

X = np.array([['madrid' ],
              ['londres'],
              ['madrid'],
              ['paris' ]])

OrdinalEncoder().fit_transform(X)

array([[1.],
       [0.],
       [1.],
       [2.]])

No obstante, esta transformación debe realizarse con cuidado, pues asigna un orden a sus elementos. En el ejemplo anterior, se ha establecido `londres = 0`, `madrid = 1` y `paris = 2`, lo que da "más peso" a París que a Madrid o Londres.

El `OrdinalEnconder` debe emplearse cuando los valores de la característica a transformar puedan ordenarse. Por ejemplo:

In [4]:
# Falla si X es np.array

X = [['deficiente' ],
     ['correcto'],
     ['muy deficiente'],
     ['mejorable' ]]

OrdinalEncoder(categories=[['muy deficiente', 'deficiente', 'mejorable', 'correcto']]).fit_transform(X)

array([[1.],
       [3.],
       [0.],
       [2.]])

## LabelEncoder

El [`LabelEnconder`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html) funciona de manera análoga al `OrdinalEnconder` pero esta pensado para transformar arrays uni-dimensionales. En general, se usa para transformar la variable objetivo (*y*) en problemas de clasificación:

In [5]:
import numpy as np
from sklearn.preprocessing import LabelEncoder


X = np.array(['positivo', 'positivo', 'neutro', 'negativo'])

LabelEncoder().fit_transform(X)

array([2, 2, 1, 0])

<hr>

Creado por **Fernando Ortega** (fernando.ortega@upm.es)

<img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png">